### ISSUE TITLE
umodel 导出 mesh 失败

### ISSUE THREAD

**Issue by notnotype** [Gktwo/Calabiyau-Assets#2]
使用 umodel 导出模型的时候出错，卡拉彼丘版本是：0.10.1.8，umodel 用的是 git 仓库的版本，umodel 里面引擎勾选了 ue4 4.25 版本

![Snipaste_2023-11-11_03-33-20](https://github.com/Gktwo/Calabiyau-Assets/assets/53962334/f0f1e842-53c2-4cad-b089-d98143df3f9f)
![Snipaste_2023-11-11_03-34-27](https://github.com/Gktwo/Calabiyau-Assets/assets/53962334/c041dcf0-9477-46d3-8676-9007591211dd)
![Snipaste_2023-11-11_03-35-01](https://github.com/Gktwo/Calabiyau-Assets/assets/53962334/eb3a7d9c-d526-440d-b396-f34a161071c2)
![Snipaste_2023-11-11_03-35-24](https://github.com/Gktwo/Calabiyau-Assets/assets/53962334/7f1a70d3-960a-4d8e-9f9d-041135ae20e5)

```code
******** Loading object SkeletalMesh4'KokonaShiki_Mesh_056.KokonaShiki_Mesh_056' ********
*** ERROR: Package "/PM/Content/PaperMan/SkinAssets/Characters/KokonaShiki/S056/Mesh3D/KokonaShiki_Mesh_056.uasset": wrong name index -12
UnPackage::SerializeFName: pos=00311ED9 <- FSkeletalMaterial<< <- TArray::Serialize: 1/12 <- USkeletalMesh4::Serialize <- LoadObject: SkeletalMesh4'KokonaShiki_Mesh_056.KokonaShiki_Mesh_056', pos=311ED9, ver=518/0 (unversioned), game=ue4.25 <- UObject::EndLoad <- LoadWholePackage: /PM/Content/PaperMan/SkinAssets/Characters/KokonaShiki/S056/Mesh3D/KokonaShiki_Mesh_056.uasset <- CUmodelApp::ShowPackageUI <- Main: umodel_build=1579 based
```

**Comment by Gktwo** [comment]
有个专属版本号就叫calabiyau，导出某些配置不兼容的文件可能也会报错

**Comment by notnotype** [comment]
谢谢，umodel_materials.exe 版本号选择 calabiyau 就可以导出了
